name: Run CI

on:
  pull_request:
    branches: ['main']

jobs:
  run-checks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.5.0'
      - run: npm ci
      - run: npx nx-cloud start-ci-run
      - run: |
         npx nx run shop-e2e:e2e:ci
      - run: ls dist/cypress/apps/shop-e2e
        if: ${{ always() }}
      - name: Stop all running agents for this CI run
        if: ${{ always() }}
        run: npx nx-cloud stop-all-agents
  agent-1:
    name: Agent 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npm ci
      - run: mkdir -p dist/cypress/apps/shop-e2e && touch dist/cypress/apps/shop-e2e/from-agent.txt
      - run: npx nx-cloud start-agent
